apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
  - schedulerName: schedulab-scheduler
    plugins:
      preEnqueue:
        disabled:
          - name: DynamicResources
      queueSort:
        disabled:
          - name: "*"
        enabled:
          - name: Schedulab
      preFilter:
        disabled:
          - name: DynamicResources
      filter:
        disabled:
          - name: DynamicResources
        enabled:
          - name: Schedulab
      postFilter:
        disabled:
          - name: DynamicResources
      score:
        disabled:
          - name: DynamicResources
        enabled:
          - name: Schedulab
            weight: 2
      reserve:
        disabled:
          - name: DynamicResources
        enabled:
          - name: Schedulab
      permit:
        enabled:
          - name: Schedulab
      preBind:
        disabled:
          - name: DynamicResources
      bind:
        disabled:
          - name: DefaultBinder
        enabled:
          - name: Schedulab
    pluginConfig:
      - name: Schedulab
        args:
          mode: balanced
          bindPods: true
          maxCPUUtilization: 90
          maxMemoryUtilization: 90
          cpuWeight: 45
          memoryWeight: 35
          spreadWeight: 20
          permitWaitSeconds: 0
          permitTimeoutSeconds: 5
          maxReservationsPerNode: 0

