apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-schedulab
  namespace: schedulab-bench
spec:
  replicas: 30
  selector:
    matchLabels:
      app: benchmark-schedulab
  template:
    metadata:
      labels:
        app: benchmark-schedulab
    spec:
      schedulerName: schedulab-scheduler
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10
          resources:
            requests:
              cpu: 20m
              memory: 32Mi

